from model.da.callprice_da import CallPriceDa
from model.da.client_da import ClientDa
from model.da.producer_da import ProducerDa
from model.da.producer_productclass_da import ProducerProductClassDa
from model.da.product_classification_da import ProductClassificationDa
from model.da.project_da import ProjectDa
from model.da.projectclient_da import ProjectClientDa
from model.da.requiredproduct_da import RequiredProductDa
from model.da.supplier_da import SupplierDa
from model.da.supplier_producerproduct_da import SupplierProducerProductDa
from model.da.supplier_productclass_da import SupplierProductClassDa
